server:
  port: 8080
spring:
  application:
    name: "dojoCA"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  data:
    mongodb:
      uri: "mongodb+srv://mikearango123:m123456@clusterbd.hstuodc.mongodb.net/?retryWrites=true&w=majority"
      database: angularsofka
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
